tech_prommux_dynamic_report:
    default_template: default
    templates:
        default:
            path: 'default.html.twig'
            name: 'Default Template with 1 column'
            containers:
                 content_top:
                     name: Top content
                 content:
                     name: Main content
                 content_bottom:
                     name: Bottom content
            matrix:
                 layout: |
                     TTTTTTTT
                     CCCCCCCC
                     BBBBBBBB
                 mapping:
                     T: content_top
                     C: content
                     B: content_bottom

        default_2columns:
            path: '2columns.html.twig'
            name: 'Default Template with 2 columns'
            containers:
                 content_top:
                     name: Top content
                 left_col:
                     name: Left content
                 right_col:
                     name: Right content
                 content_bottom:
                     name: Bottom content
            matrix:
                 layout: |
                     TTTTTTTT
                     LLLLRRRR
                     BBBBBBBB
                 mapping:
                     T: content_top
                     L: left_col
                     R: rigth_col
                     B: content_bottom
    