imports:
    - { resource: 'services_admins.yml'}
    - { resource: 'services_managers.yml'}
    - { resource: 'services_types_components.yml'}

services:
#    tech_promux_dynamic_report.example:
#        class:  TechPromux\DynamicReportBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
