services:
    # Manager Services

    techpromux_dynamic_report.manager.util_dynamic_report:
        class:  TechPromux\DynamicReportBundle\Manager\UtilDynamicReportManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setComponentManager,['@techpromux_dynamic_report.manager.component']]
            - [ setSecurityManager,['@techpromux_base.manager.default_security']]

    techpromux_dynamic_report.manager.report:
        class:  TechPromux\DynamicReportBundle\Manager\ReportManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setResourceContextManager,['@techpromux_base.manager.resource_context']]
            - [ setUtilDynamicReportManager,['@techpromux_dynamic_report.manager.util_dynamic_report']]

    techpromux_dynamic_report.manager.component:
        class:  TechPromux\DynamicReportBundle\Manager\ComponentManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setReportManager,['@techpromux_dynamic_report.manager.report']]
            - [ setDataModelManager,['@techpromux_dynamic_query.manager.datamodel']]
            - [ setUtilDynamicReportManager,['@techpromux_dynamic_report.manager.util_dynamic_report']]

