services:
#    tech_prommux_dynamic_report.example:
#        class: TechPromux\Bundle\DynamicReportBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    # Manager Services
    
    techprommux_dynamic_report.manager.report:
        class: TechPromux\Bundle\DynamicReportBundle\Manager\ReportManager
        tags:
            - { name: tech_prommux.entity_manager}
        calls:
            - [ setComponentManager,[@techprommux_dynamic_report.manager.reportcomponent]]
            - [ setDataModelManager,[@techprommux_dynamic_query.manager.query]]
            
    techprommux_dynamic_report.manager.reportcomponent:
        class: TechPromux\Bundle\DynamicReportBundle\Manager\ComponentManager
        tags:
            - { name: tech_prommux.entity_manager}
        calls:
            - [ setReportManager,[@techprommux_dynamic_report.manager.report]]
            

    # Admin Services
    
    techpromux_dynamic_report.admin.report:
        class: TechPromux\Bundle\DynamicReportBundle\Admin\ReportAdmin
        arguments: [~, TechPromux\Bundle\DynamicReportBundle\Entity\Report, TechPromuxDynamicReportBundle:ReportAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: techpromux_dynamic_report_admin, label: Report List}
        calls:
            - [ setManager,[@techprommux_dynamic_report.manager.report]]
            - [ addChild, [@techpromux_dynamic_report.admin.reportcomponent] ]

    techpromux_dynamic_report.admin.reportcomponent:
        class: TechPromux\Bundle\DynamicReportBundle\Admin\ComponentAdmin
        arguments: [~, TechPromux\Bundle\DynamicReportBundle\Entity\Component, TechPromuxDynamicReportBundle:ComponentAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: techpromux_dynamic_report_admin, label: Report Component List}
        calls:
            - [ setManager,[@techprommux_dynamic_report.manager.reportcomponent]]

    # Component Services

    tech_prommux_dynamic_report.component.simple_paginated_table:
        class: TechPromux\Bundle\DynamicReportBundle\ComponentBlock\Table\SimplePaginatedTableComponentBlock
        arguments:
            - tech_prommux_dynamic_report.component.simple_paginated_table
        tags:
            - { name: tech_prommux.dynamic_report_component }
        calls:
            - [ setComponentManager, [@techprommux_dynamic_report.manager.reportcomponent] ]

    tech_prommux_dynamic_report.component.crossed_table:
        class: TechPromux\Bundle\DynamicReportBundle\ComponentBlock\Table\CrossedTableComponentBlock
        arguments:
            - tech_prommux_dynamic_report.component.crossed_table
        tags:
            - { name: tech_prommux.dynamic_report_component }
        calls:
            - [ setComponentManager, [@techprommux_dynamic_report.manager.reportcomponent] ]

    tech_prommux_dynamic_report.component.line_chart:
        class: TechPromux\Bundle\DynamicReportBundle\ComponentBlock\Chart\LineChartComponentBlock
        arguments:
            - tech_prommux_dynamic_report.component.line_chart
        tags:
            - { name: tech_prommux.dynamic_report_component }
        calls:
            - [ setComponentManager, [@techprommux_dynamic_report.manager.reportcomponent] ]

    tech_prommux_dynamic_report.component.bar_chart:
        class: TechPromux\Bundle\DynamicReportBundle\ComponentBlock\Chart\BarChartComponentBlock
        arguments:
            - tech_prommux_dynamic_report.component.bar_chart
        tags:
            - { name: tech_prommux.dynamic_report_component }
        calls:
            - [ setComponentManager, [@techprommux_dynamic_report.manager.reportcomponent] ]

    tech_prommux_dynamic_report.component.radar_chart:
        class: TechPromux\Bundle\DynamicReportBundle\ComponentBlock\Chart\RadarChartComponentBlock
        arguments:
            - tech_prommux_dynamic_report.component.radar_chart
        tags:
            - { name: tech_prommux.dynamic_report_component }
        calls:
            - [ setComponentManager, [@tech_prommux_dynamic_report.manager.reportcomponent] ]

    tech_prommux_dynamic_report.component.rounded_chart:
        class: TechPromux\Bundle\DynamicReportBundle\ComponentBlock\Chart\RoundedChartComponentBlock
        arguments:
            - tech_prommux_dynamic_report.component.rounded_chart
        tags:
            - { name: tech_prommux.dynamic_report_component }
        calls:
            - [ setComponentManager, [@tech_prommux_dynamic_report.manager.reportcomponent] ]

    tech_prommux_dynamic_report.component.scatter_chart:
        class: TechPromux\Bundle\DynamicReportBundle\ComponentBlock\Chart\ScatterChartComponentBlock
        arguments:
            - tech_prommux_dynamic_report.component.scatter_chart
        tags:
            - { name: tech_prommux.dynamic_report_component }
        calls:
            - [ setComponentManager, [@tech_prommux_dynamic_report.manager.reportcomponent] ]

