<?php

namespace TechPromux\DynamicReportBundle\Type\Component\Chart;

use Symfony\Component\HttpFoundation\Request;
use TechPromux\DynamicReportBundle\Entity\Component;

class BarChartSeriesCrossedDatasetComponentType extends AbstractBarChartDatasetComponentType
{

    /**
     * @return string
     */
    public function getId()
    {
        return 'techpromux.chart.bar_series_crossed_dataset';
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return 'chart.bar_series_crossed_dataset';
    }

    /**
     * @return boolean
     */
    public function getHasDataModelDatasetLabel()
    {
        return true;
    }

    /**
     * @return boolean
     */
    public function getHasDataModelDatasetSeries()
    {
        return true;
    }

    /**
     * @return boolean
     */
    public function getHasDataModelDatasetMultipleDatas()
    {
        return false;
    }


    protected function getMergedDataParametersAndSettings(Request $request = null, Component $component, array $parameters = array(), $full_exportable_data = false)
    {
        $all = parent::getMergedDataParametersAndSettings($request, $component, $parameters, $full_exportable_data); // TODO: Change the autogenerated stub

        $all['settings']['_chart_dataset_type'] = 'crossed';

        return $all;
    }

}